# Default Profile
[profile.default]
solc-version = "0.8.22"
optimizer = true
optimizer-runs = 1_000
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'

# Gas reporting
gas_reports = [
  "ContractFactory",
  "Registry",
  "Allo",
  "RFPSimpleStrategy",
  "RFPCommitteeStrategy",
  "QVSimpleStrategy",
  "DonationVotingMerkleDistributionDirectTransferStrategy",
  "DonationVotingMerkleDistributionVaultStrategy",
  "QVImpactStreamStrategy",
  "RecipientSuperApp",
  "SuperAppBaseSQF",
  "SQFSuperFluidStrategy"
]
gas_reports_ignore = [
  "TestStrategy",
  "QVBaseStrategyTestMock",
  "Permit2",
  "MockStrategy",
]

# Storage layout compatibility 
build_info = true
extra_output = ["storageLayout"]
# Grants access to solc
allow_paths = ['node_modules']

[fmt]


[fuzz]
runs = 512

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
opgoerli = "${OPGOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"